services:

  zabbix:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    depends_on:
      - "mysql"

  mysql:
    image: mysql:oracle
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: